# Generated by Django 4.0.5 on 2022-06-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='productid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
